### ISSUE TITLE
Draft Schedule

### ISSUE THREAD

**Issue by Johnny2136** [CS-C-BDD-TDD/CICDpilot#1]
Using Project Scope planning and Project Plan Draft Notional Sprint (or Cycle) Cadence.

**Comment by kcw1003** [comment]
PMO Support schedule management team is currently drafting a formal schedule. This will be shared with the team early next week for input.

**Comment by Johnny2136** [comment]
Thats great!

**Comment by Johnny2136** [comment]
I think the draft is done waiting on feedback right ❓
